// 2. Write a program to calculate the real roots of the quadratic equation  ax2 + bx + c = 0,
// using quadratic equation.
package com.company;
import java.util.Scanner;
import java.lang.Math;
public class EX_02 {
    public static void main(String[] args) {
        Scanner m = new Scanner(System.in);
        System.out.println("Enter the values of a, b and c : ");
        float a = m.nextFloat();
        float b = m.nextFloat();
        float c = m.nextFloat();
        double discriminant = Math.pow(b, 2) - 4 * a * c;
        double root1 = (-b + Math.pow(discriminant, 0.5))/(2*a);
        double root2 = (-b - Math.pow(discriminant, 0.5))/(2*a);
        if (discriminant == 0){
            double root = (-b) / (2*a);
            System.out.println("One real solution is "+root+".");
        }
        else if(discriminant > 0){
            System.out.println("Two real solutions are "+root1+" and "+root2+".");
        }
        else
            System.out.println("We simply neglect complex values which are generated by negative discriminant.");
    }
}
